// Code generated by MockGen. DO NOT EDIT.
// Source: handlers.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2024_2_SaraFun/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockSurveyUsecase is a mock of SurveyUsecase interface.
type MockSurveyUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockSurveyUsecaseMockRecorder
}

// MockSurveyUsecaseMockRecorder is the mock recorder for MockSurveyUsecase.
type MockSurveyUsecaseMockRecorder struct {
	mock *MockSurveyUsecase
}

// NewMockSurveyUsecase creates a new mock instance.
func NewMockSurveyUsecase(ctrl *gomock.Controller) *MockSurveyUsecase {
	mock := &MockSurveyUsecase{ctrl: ctrl}
	mock.recorder = &MockSurveyUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSurveyUsecase) EXPECT() *MockSurveyUsecaseMockRecorder {
	return m.recorder
}

// AddQuestion mocks base method.
func (m *MockSurveyUsecase) AddQuestion(ctx context.Context, question models.AdminQuestion) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddQuestion", ctx, question)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddQuestion indicates an expected call of AddQuestion.
func (mr *MockSurveyUsecaseMockRecorder) AddQuestion(ctx, question interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddQuestion", reflect.TypeOf((*MockSurveyUsecase)(nil).AddQuestion), ctx, question)
}

// AddSurvey mocks base method.
func (m *MockSurveyUsecase) AddSurvey(ctx context.Context, survey models.Survey) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSurvey", ctx, survey)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddSurvey indicates an expected call of AddSurvey.
func (mr *MockSurveyUsecaseMockRecorder) AddSurvey(ctx, survey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSurvey", reflect.TypeOf((*MockSurveyUsecase)(nil).AddSurvey), ctx, survey)
}

// DeleteQuestion mocks base method.
func (m *MockSurveyUsecase) DeleteQuestion(ctx context.Context, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQuestion", ctx, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteQuestion indicates an expected call of DeleteQuestion.
func (mr *MockSurveyUsecaseMockRecorder) DeleteQuestion(ctx, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQuestion", reflect.TypeOf((*MockSurveyUsecase)(nil).DeleteQuestion), ctx, content)
}

// GetQuestions mocks base method.
func (m *MockSurveyUsecase) GetQuestions(ctx context.Context) ([]models.AdminQuestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestions", ctx)
	ret0, _ := ret[0].([]models.AdminQuestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestions indicates an expected call of GetQuestions.
func (mr *MockSurveyUsecaseMockRecorder) GetQuestions(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestions", reflect.TypeOf((*MockSurveyUsecase)(nil).GetQuestions), ctx)
}

// GetSurveyInfo mocks base method.
func (m *MockSurveyUsecase) GetSurveyInfo(ctx context.Context) (map[string]models.SurveyStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSurveyInfo", ctx)
	ret0, _ := ret[0].(map[string]models.SurveyStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSurveyInfo indicates an expected call of GetSurveyInfo.
func (mr *MockSurveyUsecaseMockRecorder) GetSurveyInfo(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSurveyInfo", reflect.TypeOf((*MockSurveyUsecase)(nil).GetSurveyInfo), ctx)
}

// UpdateQuestion mocks base method.
func (m *MockSurveyUsecase) UpdateQuestion(ctx context.Context, question models.AdminQuestion, content string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuestion", ctx, question, content)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateQuestion indicates an expected call of UpdateQuestion.
func (mr *MockSurveyUsecaseMockRecorder) UpdateQuestion(ctx, question, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuestion", reflect.TypeOf((*MockSurveyUsecase)(nil).UpdateQuestion), ctx, question, content)
}
