// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2024_2_SaraFun/internal/pkg/communications/delivery/grpc (interfaces: ReactionUseCase)

// Package communications_mocks is a generated GoMock package.
package communications_mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2024_2_SaraFun/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockReactionUseCase is a mock of ReactionUseCase interface.
type MockReactionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockReactionUseCaseMockRecorder
}

// MockReactionUseCaseMockRecorder is the mock recorder for MockReactionUseCase.
type MockReactionUseCaseMockRecorder struct {
	mock *MockReactionUseCase
}

// NewMockReactionUseCase creates a new mock instance.
func NewMockReactionUseCase(ctrl *gomock.Controller) *MockReactionUseCase {
	mock := &MockReactionUseCase{ctrl: ctrl}
	mock.recorder = &MockReactionUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReactionUseCase) EXPECT() *MockReactionUseCaseMockRecorder {
	return m.recorder
}

// AddReaction mocks base method.
func (m *MockReactionUseCase) AddReaction(arg0 context.Context, arg1 models.Reaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddReaction indicates an expected call of AddReaction.
func (mr *MockReactionUseCaseMockRecorder) AddReaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReaction", reflect.TypeOf((*MockReactionUseCase)(nil).AddReaction), arg0, arg1)
}

// CheckMatchExists mocks base method.
func (m *MockReactionUseCase) CheckMatchExists(arg0 context.Context, arg1, arg2 int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckMatchExists", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckMatchExists indicates an expected call of CheckMatchExists.
func (mr *MockReactionUseCaseMockRecorder) CheckMatchExists(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckMatchExists", reflect.TypeOf((*MockReactionUseCase)(nil).CheckMatchExists), arg0, arg1, arg2)
}

// GetMatchList mocks base method.
func (m *MockReactionUseCase) GetMatchList(arg0 context.Context, arg1 int) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMatchList", arg0, arg1)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMatchList indicates an expected call of GetMatchList.
func (mr *MockReactionUseCaseMockRecorder) GetMatchList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMatchList", reflect.TypeOf((*MockReactionUseCase)(nil).GetMatchList), arg0, arg1)
}

// GetMatchTime mocks base method.
func (m *MockReactionUseCase) GetMatchTime(arg0 context.Context, arg1, arg2 int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMatchTime", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMatchTime indicates an expected call of GetMatchTime.
func (mr *MockReactionUseCaseMockRecorder) GetMatchTime(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMatchTime", reflect.TypeOf((*MockReactionUseCase)(nil).GetMatchTime), arg0, arg1, arg2)
}

// GetMatchesBySearch mocks base method.
func (m *MockReactionUseCase) GetMatchesBySearch(arg0 context.Context, arg1 int, arg2 string) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMatchesBySearch", arg0, arg1, arg2)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMatchesBySearch indicates an expected call of GetMatchesBySearch.
func (mr *MockReactionUseCaseMockRecorder) GetMatchesBySearch(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMatchesBySearch", reflect.TypeOf((*MockReactionUseCase)(nil).GetMatchesBySearch), arg0, arg1, arg2)
}

// GetReactionList mocks base method.
func (m *MockReactionUseCase) GetReactionList(arg0 context.Context, arg1 int) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReactionList", arg0, arg1)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReactionList indicates an expected call of GetReactionList.
func (mr *MockReactionUseCaseMockRecorder) GetReactionList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReactionList", reflect.TypeOf((*MockReactionUseCase)(nil).GetReactionList), arg0, arg1)
}

// UpdateOrCreateReaction mocks base method.
func (m *MockReactionUseCase) UpdateOrCreateReaction(arg0 context.Context, arg1 models.Reaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrCreateReaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrCreateReaction indicates an expected call of UpdateOrCreateReaction.
func (mr *MockReactionUseCaseMockRecorder) UpdateOrCreateReaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrCreateReaction", reflect.TypeOf((*MockReactionUseCase)(nil).UpdateOrCreateReaction), arg0, arg1)
}
