// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package updateprofile

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson888c126aDecodeGithubComGoParkMailRu20242SaraFunInternalPkgPersonalitiesDeliveryHttpUpdateprofile(in *jlexer.Lexer, out *imgNumbers) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "number":
			out.Number = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson888c126aEncodeGithubComGoParkMailRu20242SaraFunInternalPkgPersonalitiesDeliveryHttpUpdateprofile(out *jwriter.Writer, in imgNumbers) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"number\":"
		out.RawString(prefix)
		out.Int(int(in.Number))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v imgNumbers) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson888c126aEncodeGithubComGoParkMailRu20242SaraFunInternalPkgPersonalitiesDeliveryHttpUpdateprofile(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v imgNumbers) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson888c126aEncodeGithubComGoParkMailRu20242SaraFunInternalPkgPersonalitiesDeliveryHttpUpdateprofile(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *imgNumbers) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson888c126aDecodeGithubComGoParkMailRu20242SaraFunInternalPkgPersonalitiesDeliveryHttpUpdateprofile(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *imgNumbers) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson888c126aDecodeGithubComGoParkMailRu20242SaraFunInternalPkgPersonalitiesDeliveryHttpUpdateprofile(l, v)
}
func easyjson888c126aDecodeGithubComGoParkMailRu20242SaraFunInternalPkgPersonalitiesDeliveryHttpUpdateprofile1(in *jlexer.Lexer, out *Request) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "first_name":
			out.FirstName = string(in.String())
		case "last_name":
			out.LastName = string(in.String())
		case "gender":
			out.Gender = string(in.String())
		case "age":
			out.Age = int(in.Int())
		case "target":
			out.Target = string(in.String())
		case "about":
			out.About = string(in.String())
		case "birth_date":
			out.BirthDate = string(in.String())
		case "imgNumbers":
			if in.IsNull() {
				in.Skip()
				out.ImgNumbers = nil
			} else {
				in.Delim('[')
				if out.ImgNumbers == nil {
					if !in.IsDelim(']') {
						out.ImgNumbers = make([]imgNumbers, 0, 4)
					} else {
						out.ImgNumbers = []imgNumbers{}
					}
				} else {
					out.ImgNumbers = (out.ImgNumbers)[:0]
				}
				for !in.IsDelim(']') {
					var v1 imgNumbers
					(v1).UnmarshalEasyJSON(in)
					out.ImgNumbers = append(out.ImgNumbers, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson888c126aEncodeGithubComGoParkMailRu20242SaraFunInternalPkgPersonalitiesDeliveryHttpUpdateprofile1(out *jwriter.Writer, in Request) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"first_name\":"
		out.RawString(prefix)
		out.String(string(in.FirstName))
	}
	{
		const prefix string = ",\"last_name\":"
		out.RawString(prefix)
		out.String(string(in.LastName))
	}
	{
		const prefix string = ",\"gender\":"
		out.RawString(prefix)
		out.String(string(in.Gender))
	}
	{
		const prefix string = ",\"age\":"
		out.RawString(prefix)
		out.Int(int(in.Age))
	}
	{
		const prefix string = ",\"target\":"
		out.RawString(prefix)
		out.String(string(in.Target))
	}
	{
		const prefix string = ",\"about\":"
		out.RawString(prefix)
		out.String(string(in.About))
	}
	{
		const prefix string = ",\"birth_date\":"
		out.RawString(prefix)
		out.String(string(in.BirthDate))
	}
	{
		const prefix string = ",\"imgNumbers\":"
		out.RawString(prefix)
		if in.ImgNumbers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.ImgNumbers {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Request) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson888c126aEncodeGithubComGoParkMailRu20242SaraFunInternalPkgPersonalitiesDeliveryHttpUpdateprofile1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Request) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson888c126aEncodeGithubComGoParkMailRu20242SaraFunInternalPkgPersonalitiesDeliveryHttpUpdateprofile1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Request) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson888c126aDecodeGithubComGoParkMailRu20242SaraFunInternalPkgPersonalitiesDeliveryHttpUpdateprofile1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Request) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson888c126aDecodeGithubComGoParkMailRu20242SaraFunInternalPkgPersonalitiesDeliveryHttpUpdateprofile1(l, v)
}
